name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout homelab
        uses: actions/checkout@v2
        with:
          repository: mgbowman/homelab
          path: homelab
      - 
        name: Checkout matchbox
        uses: actions/checkout@v2
        with:
          repository: poseidon/matchbox
          path: matchbox
      - 
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64,arm
      - 
        name: Setup Docker Multi-Arch Builder
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - 
        name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build matchbox Go binary
        run: make -C matchbox build
      -
        name: Build and push matchbox images
        uses: docker/build-push-action@v2
        with:
          file: matchbox/Dockerfile
          context: matchbox
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
          push: true
          tags: mgbowman/matchbox:latest
      -
        name: Download TFTP binaries
        run: make -C matchbox/contrib/dnsmasq/ tftp
      -
        name: Build and push matchbox-dnsmasq images
        uses: docker/build-push-action@v2
        with:
          file: matchbox/contrib/dnsmasq/Dockerfile
          context: matchbox/contrib/dnsmasq/
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
          push: true
          tags: mgbowman/matchbox-dnsmasq:latest          
